# TASK 6:Combine all 3 into one Knowledge Base

In [3]:
import sys
!{sys.executable} -m pip install kagglehub pandas

Collecting kagglehub
  Using cached kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: pandas in c:\users\famil\anaconda3\lib\site-packages (2.1.4)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Using cached kagglesdk-0.1.33-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (23.2)
Requirement already satisfied: pyyaml in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (2.33.0)
Requirement already satisfied: tqdm in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (4.67.3)
Collecting numpy<2,>=1.23.2 (from pandas)
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: protobuf in c:\users\famil\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: six>=1.5 in c:\users\famil\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in c:\users\famil\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Using cached kagglehub-1.0.2-py3-none-any.whl (70 kB)
Using cached kagglesdk-0.1.33-py3-none-any.whl (243 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB 8.6 MB/s eta 0:00:02
   - -------------------------------------- 0.5/15.8 MB 7.8 MB/s eta 0:00:02
   - -------------------------------------- 0.7/15.8 MB 6.6 MB/s eta 0:00:03
   -- ------------------------------------- 1.1/15.8 MB 7.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.5/15.8 MB 6.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/15.8 MB 7.2 MB/s eta 0:00:02
   ----- ---------------------------------- 2.1/15.8 MB 7.1 MB/s eta 0:00:02
   ------ --------------------------------- 2.4/15.8 MB 7.1 MB/s eta 0:00:02
   ------ --------------------------------- 2.7/15.8 MB 7.1 MB/s eta 0:00:02
   -------- ------------------------------- 3.2/15.8 MB 7.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.7/15.8 MB 7.5 MB/s eta 0:00:02
   ---------- ----------------------------- 4.2/15.8 MB 7.8 MB/s eta 0:00:02
   ----------- ---------------------------- 4.5/15.8 MB 7.8 MB/s eta 0:00:02
   ------------- -------------------------- 5.2/15.8 MB 8.1 MB/s eta 0:00:02
   -------------- ------------------------- 5.5/15.8 MB 8.0 MB/s eta 0:00:02
   --------------- ------------------------ 6.1/15.8 MB 8.5 MB/s eta 0:00:02
   ---------------- ----------------------- 6.5/15.8 MB 8.3 MB/s eta 0:00:02
   ----------------- ---------------------- 6.7/15.8 MB 8.1 MB/s eta 0:00:02
   ----------------- ---------------------- 7.0/15.8 MB 8.1 MB/s eta 0:00:02
   ------------------ --------------------- 7.3/15.8 MB 7.9 MB/s eta 0:00:02
   ------------------- -------------------- 7.5/15.8 MB 7.8 MB/s eta 0:00:02
   ------------------- -------------------- 7.7/15.8 MB 7.6 MB/s eta 0:00:02
   ------------------- -------------------- 7.9/15.8 MB 7.5 MB/s eta 0:00:02
   -------------------- ------------------- 8.1/15.8 MB 7.3 MB/s eta 0:00:02
   --------------------- ------------------ 8.3/15.8 MB 7.3 MB/s eta 0:00:02
   --------------------- ------------------ 8.6/15.8 MB 7.1 MB/s eta 0:00:02
   ---------------------- ----------------- 8.8/15.8 MB 7.0 MB/s eta 0:00:01
   ---------------------- ----------------- 9.0/15.8 MB 6.9 MB/s eta 0:00:01
   ----------------------- ---------------- 9.3/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 9.5/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 9.8/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------- -------------- 10.1/15.8 MB 6.8 MB/s eta 0:00:01
   -------------------------- ------------- 10.4/15.8 MB 6.8 MB/s eta 0:00:01
   -------------------------- ------------- 10.6/15.8 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 10.8/15.8 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 11.0/15.8 MB 6.6 MB/s eta 0:00:01
   ---------------------------- ----------- 11.2/15.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.5/15.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.8/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 12.0/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 12.3/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 12.5/15.8 MB 6.3 MB/s eta 0:00:01
   -------------------------------- ------- 12.7/15.8 MB 6.2 MB/s eta 0:00:01
   -------------------------------- ------- 12.9/15.8 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 13.0/15.8 MB 6.0 MB/s eta 0:00:01
   --------------------------------- ------ 13.2/15.8 MB 5.9 MB/s eta 0:00:01
   --------------------------------- ------ 13.4/15.8 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 13.5/15.8 MB 5.7 MB/s eta 0:00:01
   ---------------------------------- ----- 13.6/15.8 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 13.7/15.8 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.8/15.8 MB 5.4 MB/s eta 0:00:01
   ----------------------------------- ---- 13.9/15.8 MB 5.4 MB/s eta 0:00:01
   ----------------------------------- ---- 14.1/15.8 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.2/15.8 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 14.3/15.8 MB 5.1 MB/s eta 0:00:01
   ------------------------------------ --- 14.5/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.6/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.8/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 15.0/15.8 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 15.3/15.8 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  15.6/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 4.5 MB/s eta 0:00:00
Installing collected packages: numpy, kagglesdk, kagglehub
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
Successfully installed kagglehub-1.0.2 kagglesdk-0.1.33 numpy-1.26.4

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\anaconda3\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\AppData\Local\Temp\pip-uninstall-ijpx_gfb'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
langchain 0.1.16 requires langchain-community<0.1,>=0.0.32, which is not installed.
gradio 6.0.1 requires pydantic<=2.12.4,>=2.11.10, but you have pydantic 2.12.5 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
streamlit 1.51.0 requires pyarrow<22,>=7.0, but you have pyarrow 23.0.1 which is incompatible.

In [2]:
import sys
print(sys.executable)

C:\Users\famil\anaconda3\python.exe

In [4]:
import kagglehub
import pandas as pd
print("All good, ready to go!")

All good, ready to go!

In [5]:
import kagglehub

# Download the full dataset (it's small - ~72MB total)
path = kagglehub.dataset_download("saurabhshahane/long-lived-bug-prediction")
print("Dataset downloaded to:", path)

Downloading to C:\Users\famil\.cache\kagglehub\datasets\saurabhshahane\long-lived-bug-prediction\1.archive...

100%|█████████████████████████████████████████████████████████████████████████████| 20.8M/20.8M [00:04<00:00, 4.39MB/s]

Extracting files...

Dataset downloaded to: C:\Users\famil\.cache\kagglehub\datasets\saurabhshahane\long-lived-bug-prediction\versions\1

In [43]:
'''import pandas as pd
mozilla_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

print(mozilla_df.head())

print( eclipse_df.head())'''




import pandas as pd
mozilla_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

mozilla_df.head()

(9999, 19)
(9776, 19)

,bug_id,creation_date,component_name,product_name,short_description,long_description,assignee_name,reporter_name,resolution_category,resolution_code,status_category,status_code,update_date,quantity_of_votes,quantity_of_comments,resolution_date,bug_fix_time,severity_category,severity_code
0,BUGZILLA-294734,2005-05-18,Bugzilla-General,BUGZILLA,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,mkanat,mkanat,fixed,1,resolved,4,2005-05-19,0,15,2005-05-19,1,blocker,6
1,OTHER_APPLICATIONS-363323,2006-12-09,DOM Inspector,OTHER_APPLICATIONS,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,sdwilsh,sdwilsh,fixed,1,resolved,4,2011-06-01,0,8,2007-01-14,36,normal,2
2,SUPPORT.MOZILLA.ORG-398246,2007-10-02,General,SUPPORT.MOZILLA.ORG,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,morgamic,morgamic,fixed,1,resolved,4,2009-11-02,0,23,2008-03-24,174,blocker,6
3,RELEASE_ENGINEERING-525991,2009-11-02,General,RELEASE_ENGINEERING,Create Major Update from 3.0.15 to 3.5.5,NaN,catlee,catlee,fixed,1,resolved,4,2013-08-12,0,7,2009-11-10,8,normal,2
4,OTHER_APPLICATIONS-318859,2005-12-02,ChatZilla,OTHER_APPLICATIONS,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,gijskruitbosch+bugs,dafydd,fixed,1,resolved,4,2006-02-10,0,14,2005-12-07,5,normal,2

In [44]:
apache_df = pd.read_csv(r"D:/issues.csv", nrows=10000)
print(apache_df.shape)
apache_df.head()

#apache_df.describe()

(10000, 37)

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,...,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
0,12451174,WW-712,Update config browser to work with the new syntax,1.0,A fix for this issue is checked into the tree ...,Fixed,4.0,Minor,[],632ec9dd,...,WW,Struts 2,10380.0,struts.apache.org,Struts Framework,2005-01-01 07:50:46,0,2005-01-01 07:47:50,2005-01-01 07:50:46,The config browser used Velocity calling the t...
1,29159,XALANC-446,XALAN_C 1.9 or current do not build on Fedora ...,1.0,A fix for this issue is checked into the tree ...,Fixed,1.0,Blocker,[],NaN,...,XALANC,XalanC,11460.0,Xalan Related Projects,Xalan,2004-12-30 05:30:36,1,2004-12-25 22:50:30,2005-01-01 10:20:52,Two types of errors:\n1- runConfigure and conf...
2,12420130,ROL-587,"Problem with ADD new post, and DELETE post.",5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,2.0,Critical,[],4d4054ac,...,ROL,Apache Roller,10331.0,NaN,Roller,2005-01-02 15:21:00,0,2005-01-01 13:52:46,2005-01-02 15:21:00,"When trying to add new post, I was getting nex..."
3,29222,AXIS-1741,LogHandler can only work in GlobalConfiguratio...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,0,2005-01-02 19:13:37,2005-01-02 19:35:36,org.apache.axis.handlers.LogHandler in request...
4,29233,AXIS-1745,Decoding of service is broken in org.apache.ax...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,1,2005-01-03 03:34:52,2005-01-03 03:34:52,The following code assumes a lot of things:\n\...

In [34]:
mozilla_df.columns
mozilla_df['status_category']

0       resolved
1       resolved
2       resolved
3       resolved
4       resolved
          ...
9994    resolved
9995    resolved
9996    resolved
9997    resolved
9998    resolved
Name: status_category, Length: 9999, dtype: object

In [42]:
print(mozilla_df.columns)
print(apache_df.columns)
apache_df[['resolution.id', 'resolution.description',
       'resolution.name','statusCategory.name']]

Index(['bug_id', 'creation_date', 'component_name', 'product_name',
       'short_description', 'long_description', 'assignee_name',
       'reporter_name', 'resolution_category', 'resolution_code',
       'status_category', 'status_code', 'update_date', 'quantity_of_votes',
       'quantity_of_comments', 'resolution_date', 'bug_fix_time',
       'severity_category', 'severity_code'],
      dtype='object')
Index(['id', 'key', 'summary', 'resolution.id', 'resolution.description',
       'resolution.name', 'priority.id', 'priority.name', 'labels', 'assignee',
       'status.id', 'status.description', 'status.name', 'statusCategory.id',
       'statusCategory.key', 'statusCategory.colorName', 'statusCategory.name',
       'customfield_12310921', 'creator', 'subtasks', 'reporter',
       'votes.votes', 'issuetype.id', 'issuetype.description',
       'issuetype.name', 'issuetype.subtask', 'project.id', 'project.key',
       'project.name', 'projectCategory.id', 'projectCategory.description',
       'projectCategory.name', 'resolutiondate', 'watches.watchCount',
       'created', 'updated', 'description'],
      dtype='object')

,resolution.id,resolution.description,resolution.name,statusCategory.name
0,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
1,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
2,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
3,NaN,NaN,NaN,To Do
4,NaN,NaN,NaN,To Do
...,...,...,...,...
9995,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9996,3.0,The problem is a duplicate of an existing issue.,Duplicate,Done
9997,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9998,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
9999,1.0,A fix for this issue is checked into the tree ...,Fixed,Done

In [40]:
mozilla_std = pd.DataFrame({
    'bug_id':mozilla_df['bug_id'],
    'title':mozilla_df['short_description'],
    'description':mozilla_df['long_description'],
    'severity':mozilla_df['severity_category'],
    'resolution':mozilla_df['resolution_category'],
    'status':mozilla_df['status_category'],
    'source_dataset':'Mozilla'
}
    
)

eclipse_std = pd.DataFrame({
    'bug_id':eclipse_df['bug_id'],
    'title':eclipse_df['short_description'],
    'description':eclipse_df['long_description'],
    'severity':eclipse_df ['severity_category'],
    'resolution':eclipse_df['resolution_category'],
    'status':eclipse_df['status_category'],
    'source_dataset':'Eclipse'
}
    
)

apache_std = pd.DataFrame({
    'bug_id':apache_df['key'],
    'title':apache_df['summary'],
    'description':apache_df['description'],
    'severity':apache_df ['priority.name'],
    'resolution':apache_df['resolution.name'],
    'status':apache_df['statusCategory.name'],
    'source_dataset':'Apache'
    
})

print('Mozilla:',mozilla_std.shape)
print('Eclipse:',eclipse_std.shape)
print('Apache:',apache_std.shape)

Mozilla: (9999, 7)
Eclipse: (9776, 7)
Apache: (10000, 7)

In [45]:
mozilla_std['stack_trace'] = None
eclipse_std['stack_trace'] = None
apache_std['stack_trace'] = None

mozilla_std['product_component'] = mozilla_df['product_name']
eclipse_std['product_component'] = eclipse_df['product_name']
apache_std['product_component'] = apache_df['project.name']


print(mozilla_std.shape)
print(eclipse_std.shape)
print(apache_std.shape)

mozilla_std.head()

(9999, 9)
(9776, 9)
(10000, 9)

,bug_id,title,description,severity,resolution,status,source_dataset,stack_trace,product_component
0,BUGZILLA-294734,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,blocker,fixed,resolved,Mozilla,None,BUGZILLA
1,OTHER_APPLICATIONS-363323,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS
2,SUPPORT.MOZILLA.ORG-398246,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,blocker,fixed,resolved,Mozilla,None,SUPPORT.MOZILLA.ORG
3,RELEASE_ENGINEERING-525991,Create Major Update from 3.0.15 to 3.5.5,NaN,normal,fixed,resolved,Mozilla,None,RELEASE_ENGINEERING
4,OTHER_APPLICATIONS-318859,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS

In [47]:
knowledge_base_df = pd.concat([mozilla_std,eclipse_std,apache_std], ignore_index = True)
print("Comobo Size " , knowledge_base_df.shape)
knowledge_base_df['source_dataset'].value_counts()

Comobo Size  (29775, 9)

source_dataset
Apache     10000
Mozilla     9999
Eclipse     9776
Name: count, dtype: int64

In [60]:
knowledge_base_df.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_basic_combined.csv" , index = False)
print("Saved Sucessfully")

Saved Sucessfully

# TASK 7:DATA CLEANING

In [54]:
print(knowledge_base_df.isnull().sum())
print("\n\nDuplicate id : ",knowledge_base_df['bug_id'].duplicated().sum())
print("\n\nShape before cleaning : ",knowledge_base_df.shape)

bug_id                   0
title                    1
description            613
severity               354
resolution            1036
status                1036
source_dataset           0
stack_trace          29775
product_component        0
dtype: int64


Duplicate id :  0


Shape before cleaning :  (29775, 9)

In [57]:
knowledge_base_clean = knowledge_base_df.dropna(subset = ['title','description'])

knowledge_base_clean = knowledge_base_clean.fillna({
    'severity':'Unknown',
    'resolution':'Not Specificed',
    'status':'Unknown'
})

print("Shape after cleaning :",knowledge_base_clean.shape)
print("\nRemaining nulls : \n",knowledge_base_clean.isnull().sum())

Shape after cleaning : (29161, 9)

Remaining nulls :
 bug_id                   0
title                    0
description              0
severity                 0
resolution               0
status                   0
source_dataset           0
stack_trace          29161
product_component        0
dtype: int64

In [58]:
import re

def clean_text(text):
    if pd.isna(text):
        return(text)
    text =  str(text)
    text = re.sub(r'<[^>]+>',' ',text)
    text = re.sub(r'\s+',' ',text)
    return text.strip()

knowledge_base_clean['title'] = knowledge_base_clean['title'].apply(clean_text)
knowledge_base_clean['description'] = knowledge_base_clean['description'].apply(clean_text)

print('Cleaning applied . A Sample of that :')
knowledge_base_clean[['title','description']].head(3)

Cleaning applied . A Sample of that :

,title,description
0,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...
1,DOM View is really inefficient with setting wh...,From comment in url: Current code: menuitem ->...
2,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...

In [61]:
knowledge_base_clean.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_base_cleaned.csv" , index = False)
print("Saved Cleaned knowledge Base")

Saved Cleaned knowledge Base

# TASK 8:Chunking with  Langchain

In [62]:
import sys
!{sys.executable} -m pip install langchain langchain-text-splitters

Requirement already satisfied: langchain in c:\users\famil\anaconda3\lib\site-packages (0.1.16)
Requirement already satisfied: langchain-text-splitters in c:\users\famil\anaconda3\lib\site-packages (0.0.2)
Requirement already satisfied: PyYAML>=5.3 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (6.0.1)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (2.0.25)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (3.9.3)
Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (0.6.7)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (1.33)
Collecting langchain-community<0.1,>=0.0.32 (from langchain)
  Using cached langchain_community-0.0.38-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: langchain-core<0.2.0,>=0.1.42 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (0.1.53)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (0.1.147)
Requirement already satisfied: numpy<2,>=1 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (1.26.4)
Requirement already satisfied: pydantic<3,>=1 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: requests<3,>=2 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (2.33.0)
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in c:\users\famil\anaconda3\lib\site-packages (from langchain) (8.5.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\famil\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.9.3)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\famil\anaconda3\lib\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\famil\anaconda3\lib\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain) (0.9.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\famil\anaconda3\lib\site-packages (from jsonpatch<2.0,>=1.33->langchain) (2.1)
Requirement already satisfied: packaging<24.0,>=23.2 in c:\users\famil\anaconda3\lib\site-packages (from langchain-core<0.2.0,>=0.1.42->langchain) (23.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\famil\anaconda3\lib\site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\users\famil\anaconda3\lib\site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (3.11.4)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\users\famil\anaconda3\lib\site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\famil\anaconda3\lib\site-packages (from pydantic<3,>=1->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (2.0.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\famil\anaconda3\lib\site-packages (from requests<3,>=2->langchain) (2026.2.25)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\famil\anaconda3\lib\site-packages (from SQLAlchemy<3,>=1.4->langchain) (3.0.1)
Requirement already satisfied: anyio in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\users\famil\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\famil\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (0.16.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\famil\anaconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain) (1.0.0)
Using cached langchain_community-0.0.38-py3-none-any.whl (2.0 MB)
Installing collected packages: langchain-community
Successfully installed langchain-community-0.0.38

In [67]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=500 , chunk_overlap=50)

knowledge_base_clean['full_text'] = knowledge_base_clean['title'] + ". " + knowledge_base_clean['description']

sample_text = knowledge_base_clean['full_text'].iloc[0]
chunks = splitter.split_text(sample_text)

print("Original Text Length :",len(sample_text))
print("Numberof chunks :",len(chunks))
print("\nFirst Chunk:\n",chunks[0])

Original Text Length : 173
Numberof chunks : 1

First Chunk:
 Emergency 2.16.10 Release. 2.16.9 is broken -- many users can't enter bugs on it particularly not from a fresh install. So we need to pull 2.16.9 and post a 2.16.10 instead.

In [69]:
longer_text = knowledge_base_clean['full_text'].iloc[1]
chunks = splitter.split_text(longer_text)

print("Original Text Length :",len(longer_text))
print("Numberof chunks :",len(chunks))
print("\n--- Chunk 1 ---\n",chunks[0])
print("\n--- Chunk 2 ---\n",chunks[1] if len(chunks)>1 else "(only 1 chunk)")

Original Text Length : 304
Numberof chunks : 1

--- Chunk 1 ---
 DOM View is really inefficient with setting what is to be shown. From comment in url: Current code: menuitem -> command -> toggler -> setter -> pref -> observer -> setter -> pref Proposed code: menuitem -> command -> toggler -> pref -> observer -> setter arguably we should rebuild() in the observer too.

--- Chunk 2 ---
 (only 1 chunk)

In [72]:
longest_idx = knowledge_base_clean['full_text'].str.len().idxmax()
longest_text=knowledge_base_clean['full_text'].loc[longest_idx]

print("Length of longest text:", len(longest_text))  
chunks = splitter.split_text(longest_text)

print("Length of longest text:",len(chunks))
print("Number of chunks :",len(chunks))
print("\n--- Chunk 1 ---\n",chunks[0])
print("\n--- Chunk 2 ---\n",chunks[1] if len(chunks)>1 else "(only 1 chunk)")

Length of longest text: 64610
Length of longest text: 171
Number of chunks : 171

--- Chunk 1 ---
 [FIX]I am a beginner from China, and i can't work jetspeed with db2,please help me,ok?. As followed is my db2 ddl and populate file contents. CREATE TABLE TURBINE_USER ( USER_ID INTEGER NOT NULL, LOGIN_NAME VARCHAR (32) NOT NULL, PASSWORD_VALUE VARCHAR (32) NOT NULL, FIRST_NAME VARCHAR (99) NOT NULL, LAST_NAME VARCHAR (99) NOT NULL, EMAIL VARCHAR (99), CONFIRM_VALUE VARCHAR (99), MODIFIED TIMESTAMP, CREATED TIMESTAMP, LAST_LOGIN TIMESTAMP, DISABLED VARCHAR (1), OBJECTDATA CLOB(16777215),

--- Chunk 2 ---
 DISABLED VARCHAR (1), OBJECTDATA CLOB(16777215), PASSWORD_CHANGED TIMESTAMP, UNIQUE (LOGIN_NAME) ); ALTER TABLE TURBINE_USER ADD PRIMARY KEY (USER_ID); CREATE TABLE TURBINE_ROLE ( ROLE_ID INTEGER NOT NULL, ROLE_NAME VARCHAR (99) NOT NULL, OBJECTDATA CLOB(16777215), UNIQUE (ROLE_NAME) ); ALTER TABLE TURBINE_ROLE ADD PRIMARY KEY (ROLE_ID); CREATE TABLE TURBINE_GROUP ( GROUP_ID INTEGER NOT NULL, GROUP_NAME VARCHAR (99) NOT NULL, OBJECTDATA CLOB(16777215), UNIQUE (GROUP_NAME) ); ALTER TABLE

In [73]:
# Cap any single text at 3000 characters before chunking (keeps outliers from exploding chunk count)
knowledge_base_clean['full_text'] = knowledge_base_clean['full_text'].str[:3000]

In [75]:
all_chunks = []

for idx , row  in knowledge_base_clean.iterrows():
    text_chunks = splitter.split_text(row['full_text'])
    for i , chunk in enumerate(text_chunks):
        all_chunks.append({
            'chunk_id':f"{row['bug_id']}_chunk{i}",
            'bug_id':row['bug_id'],
            'chunk_text':chunk,
            'title':row['title'],
            'severity':row['severity'],
            'resolution':row['resolution'],
            'status':row['status'],
            'source_dataset':row['source_dataset']
        })

chunks_df = pd.DataFrame(all_chunks)
print("Total chunks created:",chunks_df.shape[0])
print("From original rows:", knowledge_base_clean.shape[0])
chunks_df.head(55)

Total chunks created: 56862
From original rows: 29161

,chunk_id,bug_id,chunk_text,title,severity,resolution,status,source_dataset
0,BUGZILLA-294734_chunk0,BUGZILLA-294734,Emergency 2.16.10 Release. 2.16.9 is broken --...,Emergency 2.16.10 Release,blocker,fixed,resolved,Mozilla
1,OTHER_APPLICATIONS-363323_chunk0,OTHER_APPLICATIONS-363323,DOM View is really inefficient with setting wh...,DOM View is really inefficient with setting wh...,normal,fixed,resolved,Mozilla
2,SUPPORT.MOZILLA.ORG-398246_chunk0,SUPPORT.MOZILLA.ORG-398246,Add support for custom cookies and cache heade...,Add support for custom cookies and cache headers,blocker,fixed,resolved,Mozilla
3,SUPPORT.MOZILLA.ORG-398246_chunk1,SUPPORT.MOZILLA.ORG-398246,at re-implementing some session libs I have fr...,Add support for custom cookies and cache headers,blocker,fixed,resolved,Mozilla
4,OTHER_APPLICATIONS-318859_chunk0,OTHER_APPLICATIONS-318859,DCC functionality in ChatZilla isn't functiona...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
5,OTHER_APPLICATIONS-318859_chunk1,OTHER_APPLICATIONS-318859,DCC offers matched. [18:54:22] [INFO] You must...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
6,OTHER_APPLICATIONS-318859_chunk2,OTHER_APPLICATIONS-318859,(67.186.207.96:55938) [Cancel]. [19:05:06][DCC...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
7,OTHER_APPLICATIONS-318859_chunk3,OTHER_APPLICATIONS-318859,function. Actual Results: Note that the functi...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
8,DEVELOPER.MOZILLA.ORG-416840_chunk0,DEVELOPER.MOZILLA.ORG-416840,Fix and cruft. Since we removed the breadcrumb...,Fix and cruft,normal,fixed,resolved,Mozilla
9,MARKETPLACE_GRAVEYARD-977729_chunk0,MARKETPLACE_GRAVEYARD-977729,add a waffle to disable the theme queue. This ...,add a waffle to disable the theme queue,normal,fixed,resolved,Mozilla
10,THUNDERBIRD-339875_chunk0,THUNDERBIRD-339875,ship ga-IE for 1.5.0.5. the ga-IE locale for T...,ship ga-IE for 1.5.0.5,normal,fixed,resolved,Mozilla
11,FIREFOX-420556_chunk0,FIREFOX-420556,sidebarheader on GNOME has a transparent backg...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
12,FIREFOX-420556_chunk1,FIREFOX-420556,top and bottom borders and it's unclear why th...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
13,FIREFOX-420556_chunk2,FIREFOX-420556,border rules to be applied and I looked at thr...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
14,FIREFOX-420556_chunk3,FIREFOX-420556,top and bottom border rules. Here's a patch th...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
15,FIREFOX-420556_chunk4,FIREFOX-420556,in the sidebar itself (f.e. the Search label i...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
16,MOZILLA_LOCALIZATIONS-415621_chunk0,MOZILLA_LOCALIZATIONS-415621,Firefox 3 mk release tracker. This is a tracke...,Firefox 3 mk release tracker,normal,fixed,resolved,Mozilla
17,CORE-254510_chunk0,CORE-254510,Bug 200433 regressed by patch in bug 253597. T...,Bug 200433 regressed by patch in bug 253597,major,fixed,resolved,Mozilla
18,CORE-204573_chunk0,CORE-204573,View-source highlighting is incorrect for XML ...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
19,CORE-204573_chunk1,CORE-204573,in a tag name (e. g. the attached file). Actua...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
20,CORE-204573_chunk2,CORE-204573,and Mozilla 1.0 (PC/Linux) - In the case of an...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
21,THUNDERBIRD-412434_chunk0,THUNDERBIRD-412434,opening a window with -chrome does not work an...,opening a window with -chrome does not work an...,normal,fixed,resolved,Mozilla
22,THUNDERBIRD-412434_chunk1,THUNDERBIRD-412434,but that function is defined nowhere in the fi...,opening a window with -chrome does not work an...,normal,fixed,resolved,Mozilla
23,OTHER_APPLICATIONS_GRAVEYARD-391445_chunk0,OTHER_APPLICATIONS_GRAVEYARD-391445,Unsightly border around clicked tabs. With the...,Unsightly border around clicked tabs,normal,fixed,resolved,Mozilla
24,FIREFOX_OS_GRAVEYARD-942470_chunk0,FIREFOX_OS_GRAVEYARD-942470,test_user_agent_updates.htmltest_user_agent_ov...,test_user_agent_updates.htmltest_user_agent_ov...,normal,fixed,resolved,Mozilla
25,FIREFOX_OS_GRAVEYARD-942470_chunk1,FIREFOX_OS_GRAVEYARD-942470,OS X 10.8) != -1 but intermittently instead of...,test_user_agent_updates.htmltest_user_agent_ov...,normal,fixed,resolved,Mozilla
26,TECH_EVANGELISM_GRAVEYARD-142958_chunk0,TECH_EVANGELISM_GRAVEYARD-142958,oracle.usu.ru - form is submitted incorrectly ...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
27,TECH_EVANGELISM_GRAVEYARD-142958_chunk1,TECH_EVANGELISM_GRAVEYARD-142958,is only one text field (for entering the searc...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
28,TECH_EVANGELISM_GRAVEYARD-142958_chunk2,TECH_EVANGELISM_GRAVEYARD-142958,it should looks like: 'XXX mathes found. Your ...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
29,TECH_EVANGELISM_GRAVEYARD-142958_chunk3,TECH_EVANGELISM_GRAVEYARD-142958,has an OnClick event document.forms[0].submit(...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
30,CORE-128371_chunk0,CORE-128371,menu items on the left side are not displayed....,menu items on the left side are not displayed,major,fixed,resolved,Mozilla
31,SEAMONKEY-160672_chunk0,SEAMONKEY-160672,[FIX]XP filepicker's modeGetFolder looks too m...,[FIX]XP filepicker's modeGetFolder looks too m...,normal,fixed,resolved,Mozilla
32,MOZILLA.ORG_GRAVEYARD-471000_chunk0,MOZILLA.ORG_GRAVEYARD-471000,qm-plinux-trunk04 needs a kick.. Currently unr...,qm-plinux-trunk04 needs a kick.,normal,fixed,resolved,Mozilla
33,CORE-459938_chunk0,CORE-459938,Video has incorrect colours. The video in the ...,Video has incorrect colours,normal,fixed,resolved,Mozilla
34,SEAMONKEY-57480_chunk0,SEAMONKEY-57480,problem with getting back to Font size 100% af...,problem with getting back to Font size 100% af...,normal,fixed,resolved,Mozilla
35,BUGZILLA-58242_chunk0,BUGZILLA-58242,relogin.cgi fails to delete server's copy of t...,relogin.cgi fails to delete server's copy of t...,minor,fixed,resolved,Mozilla
36,BUGZILLA-58242_chunk1,BUGZILLA-58242,SendSQL(delete from logincookies where userid=...,relogin.cgi fails to delete server's copy of t...,minor,fixed,resolved,Mozilla
37,FIREFOX_BUILD_SYSTEM-454709_chunk0,FIREFOX_BUILD_SYSTEM-454709,WinCE Resource Compiling Needs Shunt Applicati...,WinCE Resource Compiling Needs Shunt Application,normal,fixed,resolved,Mozilla
38,OTHER_APPLICATIONS-315913_chunk0,OTHER_APPLICATIONS-315913,Replace RDF userlist with direct nsITreeView i...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
39,OTHER_APPLICATIONS-315913_chunk1,OTHER_APPLICATIONS-315913,proposal is changing the tree from a content v...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
40,OTHER_APPLICATIONS-315913_chunk2,OTHER_APPLICATIONS-315913,are therefore removed in setCurrentObject my_c...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
41,OTHER_APPLICATIONS-315913_chunk3,OTHER_APPLICATIONS-315913,row as the builder view does not permit arbitr...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
42,MOZILLA.ORG_GRAVEYARD-516424_chunk0,MOZILLA.ORG_GRAVEYARD-516424,MDC badly broken this morning. MDC appears to ...,MDC badly broken this morning,blocker,fixed,resolved,Mozilla
43,MOZILLA_LOCALIZATIONS-372935_chunk0,MOZILLA_LOCALIZATIONS-372935,[ro] migration wizard string change. We want t...,[ro] migration wizard string change,normal,fixed,resolved,Mozilla
44,MOZILLA_LOCALIZATIONS-372935_chunk1,MOZILLA_LOCALIZATIONS-372935,The corresponding patch is the en-US part in h...,[ro] migration wizard string change,normal,fixed,resolved,Mozilla
45,TECH_EVANGELISM_GRAVEYARD-79139_chunk0,TECH_EVANGELISM_GRAVEYARD-79139,Danawa Korea Strict mode page has extraneous -...,Danawa Korea Strict mode page has extraneous -...,normal,fixed,resolved,Mozilla
46,CORE-353334_chunk0,CORE-353334,[FIX]Permission denied error scripting SVG fro...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
47,CORE-353334_chunk1,CORE-353334,URL-encoded SVG document. I then add the objec...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
48,CORE-353334_chunk2,CORE-353334,I have yet to see the same error when the file...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
49,MOZILLA.ORG-83075_chunk0,MOZILLA.ORG-83075,Quip List requested. Is there any list of curr...,Quip List requested,normal,fixed,resolved,Mozilla
50,CAMINO_GRAVEYARD-294848_chunk0,CAMINO_GRAVEYARD-294848,Can't override dialog warning of duplicate ssl...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
51,CAMINO_GRAVEYARD-294848_chunk1,CAMINO_GRAVEYARD-294848,for all their routers. Camino gives an error w...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
52,CAMINO_GRAVEYARD-294848_chunk2,CAMINO_GRAVEYARD-294848,use a different browser. Firefox gives a simil...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
53,CAMINO_GRAVEYARD-294848_chunk3,CAMINO_GRAVEYARD-294848,the router. Expected Results: Allow the user t...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
54,INFRASTRUCTURE_&_OPERATIONS-848951_chunk0,INFRASTRUCTURE_&_OPERATIONS-848951,remove network block for the following hosts i...,remove network block for the following hosts i...,normal,fixed,resolved,Mozilla

In [76]:
chunks_df.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/chunks_df.csv",index=False)
print("Saved Chunks")

Saved Chunks