In [3]:
import sys
!{sys.executable} -m pip install kagglehub pandas

Collecting kagglehub
  Using cached kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: pandas in c:\users\famil\anaconda3\lib\site-packages (2.1.4)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Using cached kagglesdk-0.1.33-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (23.2)
Requirement already satisfied: pyyaml in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (2.33.0)
Requirement already satisfied: tqdm in c:\users\famil\anaconda3\lib\site-packages (from kagglehub) (4.67.3)
Collecting numpy<2,>=1.23.2 (from pandas)
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\famil\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: protobuf in c:\users\famil\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: six>=1.5 in c:\users\famil\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2.0.7)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\famil\anaconda3\lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in c:\users\famil\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Using cached kagglehub-1.0.2-py3-none-any.whl (70 kB)
Using cached kagglesdk-0.1.33-py3-none-any.whl (243 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
    --------------------------------------- 0.3/15.8 MB 8.6 MB/s eta 0:00:02
   - -------------------------------------- 0.5/15.8 MB 7.8 MB/s eta 0:00:02
   - -------------------------------------- 0.7/15.8 MB 6.6 MB/s eta 0:00:03
   -- ------------------------------------- 1.1/15.8 MB 7.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.5/15.8 MB 6.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.8/15.8 MB 7.2 MB/s eta 0:00:02
   ----- ---------------------------------- 2.1/15.8 MB 7.1 MB/s eta 0:00:02
   ------ --------------------------------- 2.4/15.8 MB 7.1 MB/s eta 0:00:02
   ------ --------------------------------- 2.7/15.8 MB 7.1 MB/s eta 0:00:02
   -------- ------------------------------- 3.2/15.8 MB 7.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.7/15.8 MB 7.5 MB/s eta 0:00:02
   ---------- ----------------------------- 4.2/15.8 MB 7.8 MB/s eta 0:00:02
   ----------- ---------------------------- 4.5/15.8 MB 7.8 MB/s eta 0:00:02
   ------------- -------------------------- 5.2/15.8 MB 8.1 MB/s eta 0:00:02
   -------------- ------------------------- 5.5/15.8 MB 8.0 MB/s eta 0:00:02
   --------------- ------------------------ 6.1/15.8 MB 8.5 MB/s eta 0:00:02
   ---------------- ----------------------- 6.5/15.8 MB 8.3 MB/s eta 0:00:02
   ----------------- ---------------------- 6.7/15.8 MB 8.1 MB/s eta 0:00:02
   ----------------- ---------------------- 7.0/15.8 MB 8.1 MB/s eta 0:00:02
   ------------------ --------------------- 7.3/15.8 MB 7.9 MB/s eta 0:00:02
   ------------------- -------------------- 7.5/15.8 MB 7.8 MB/s eta 0:00:02
   ------------------- -------------------- 7.7/15.8 MB 7.6 MB/s eta 0:00:02
   ------------------- -------------------- 7.9/15.8 MB 7.5 MB/s eta 0:00:02
   -------------------- ------------------- 8.1/15.8 MB 7.3 MB/s eta 0:00:02
   --------------------- ------------------ 8.3/15.8 MB 7.3 MB/s eta 0:00:02
   --------------------- ------------------ 8.6/15.8 MB 7.1 MB/s eta 0:00:02
   ---------------------- ----------------- 8.8/15.8 MB 7.0 MB/s eta 0:00:01
   ---------------------- ----------------- 9.0/15.8 MB 6.9 MB/s eta 0:00:01
   ----------------------- ---------------- 9.3/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 9.5/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 9.8/15.8 MB 6.9 MB/s eta 0:00:01
   ------------------------- -------------- 10.1/15.8 MB 6.8 MB/s eta 0:00:01
   -------------------------- ------------- 10.4/15.8 MB 6.8 MB/s eta 0:00:01
   -------------------------- ------------- 10.6/15.8 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 10.8/15.8 MB 6.7 MB/s eta 0:00:01
   --------------------------- ------------ 11.0/15.8 MB 6.6 MB/s eta 0:00:01
   ---------------------------- ----------- 11.2/15.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.5/15.8 MB 6.5 MB/s eta 0:00:01
   ----------------------------- ---------- 11.8/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------ --------- 12.0/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 12.3/15.8 MB 6.4 MB/s eta 0:00:01
   ------------------------------- -------- 12.5/15.8 MB 6.3 MB/s eta 0:00:01
   -------------------------------- ------- 12.7/15.8 MB 6.2 MB/s eta 0:00:01
   -------------------------------- ------- 12.9/15.8 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 13.0/15.8 MB 6.0 MB/s eta 0:00:01
   --------------------------------- ------ 13.2/15.8 MB 5.9 MB/s eta 0:00:01
   --------------------------------- ------ 13.4/15.8 MB 5.8 MB/s eta 0:00:01
   ---------------------------------- ----- 13.5/15.8 MB 5.7 MB/s eta 0:00:01
   ---------------------------------- ----- 13.6/15.8 MB 5.6 MB/s eta 0:00:01
   ---------------------------------- ----- 13.7/15.8 MB 5.5 MB/s eta 0:00:01
   ---------------------------------- ----- 13.8/15.8 MB 5.4 MB/s eta 0:00:01
   ----------------------------------- ---- 13.9/15.8 MB 5.4 MB/s eta 0:00:01
   ----------------------------------- ---- 14.1/15.8 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 14.2/15.8 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 14.3/15.8 MB 5.1 MB/s eta 0:00:01
   ------------------------------------ --- 14.5/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.6/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.8/15.8 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 15.0/15.8 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 15.3/15.8 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  15.6/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  15.8/15.8 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 4.5 MB/s eta 0:00:00
Installing collected packages: numpy, kagglesdk, kagglehub
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
Successfully installed kagglehub-1.0.2 kagglesdk-0.1.33 numpy-1.26.4

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\anaconda3\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\famil\AppData\Local\Temp\pip-uninstall-ijpx_gfb'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
langchain 0.1.16 requires langchain-community<0.1,>=0.0.32, which is not installed.
gradio 6.0.1 requires pydantic<=2.12.4,>=2.11.10, but you have pydantic 2.12.5 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
streamlit 1.51.0 requires pyarrow<22,>=7.0, but you have pyarrow 23.0.1 which is incompatible.

In [2]:
import sys
print(sys.executable)

C:\Users\famil\anaconda3\python.exe

In [4]:
import kagglehub
import pandas as pd
print("All good, ready to go!")

All good, ready to go!

In [5]:
import kagglehub

# Download the full dataset (it's small - ~72MB total)
path = kagglehub.dataset_download("saurabhshahane/long-lived-bug-prediction")
print("Dataset downloaded to:", path)

Downloading to C:\Users\famil\.cache\kagglehub\datasets\saurabhshahane\long-lived-bug-prediction\1.archive...

100%|█████████████████████████████████████████████████████████████████████████████| 20.8M/20.8M [00:04<00:00, 4.39MB/s]

Extracting files...

Dataset downloaded to: C:\Users\famil\.cache\kagglehub\datasets\saurabhshahane\long-lived-bug-prediction\versions\1

In [43]:
'''import pandas as pd
mozilla_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

print(mozilla_df.head())

print( eclipse_df.head())'''




import pandas as pd
mozilla_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

mozilla_df.head()

(9999, 19)
(9776, 19)

,bug_id,creation_date,component_name,product_name,short_description,long_description,assignee_name,reporter_name,resolution_category,resolution_code,status_category,status_code,update_date,quantity_of_votes,quantity_of_comments,resolution_date,bug_fix_time,severity_category,severity_code
0,BUGZILLA-294734,2005-05-18,Bugzilla-General,BUGZILLA,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,mkanat,mkanat,fixed,1,resolved,4,2005-05-19,0,15,2005-05-19,1,blocker,6
1,OTHER_APPLICATIONS-363323,2006-12-09,DOM Inspector,OTHER_APPLICATIONS,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,sdwilsh,sdwilsh,fixed,1,resolved,4,2011-06-01,0,8,2007-01-14,36,normal,2
2,SUPPORT.MOZILLA.ORG-398246,2007-10-02,General,SUPPORT.MOZILLA.ORG,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,morgamic,morgamic,fixed,1,resolved,4,2009-11-02,0,23,2008-03-24,174,blocker,6
3,RELEASE_ENGINEERING-525991,2009-11-02,General,RELEASE_ENGINEERING,Create Major Update from 3.0.15 to 3.5.5,NaN,catlee,catlee,fixed,1,resolved,4,2013-08-12,0,7,2009-11-10,8,normal,2
4,OTHER_APPLICATIONS-318859,2005-12-02,ChatZilla,OTHER_APPLICATIONS,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,gijskruitbosch+bugs,dafydd,fixed,1,resolved,4,2006-02-10,0,14,2005-12-07,5,normal,2

In [44]:
apache_df = pd.read_csv(r"D:/issues.csv", nrows=10000)
print(apache_df.shape)
apache_df.head()

#apache_df.describe()

(10000, 37)

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,...,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
0,12451174,WW-712,Update config browser to work with the new syntax,1.0,A fix for this issue is checked into the tree ...,Fixed,4.0,Minor,[],632ec9dd,...,WW,Struts 2,10380.0,struts.apache.org,Struts Framework,2005-01-01 07:50:46,0,2005-01-01 07:47:50,2005-01-01 07:50:46,The config browser used Velocity calling the t...
1,29159,XALANC-446,XALAN_C 1.9 or current do not build on Fedora ...,1.0,A fix for this issue is checked into the tree ...,Fixed,1.0,Blocker,[],NaN,...,XALANC,XalanC,11460.0,Xalan Related Projects,Xalan,2004-12-30 05:30:36,1,2004-12-25 22:50:30,2005-01-01 10:20:52,Two types of errors:\n1- runConfigure and conf...
2,12420130,ROL-587,"Problem with ADD new post, and DELETE post.",5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,2.0,Critical,[],4d4054ac,...,ROL,Apache Roller,10331.0,NaN,Roller,2005-01-02 15:21:00,0,2005-01-01 13:52:46,2005-01-02 15:21:00,"When trying to add new post, I was getting nex..."
3,29222,AXIS-1741,LogHandler can only work in GlobalConfiguratio...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,0,2005-01-02 19:13:37,2005-01-02 19:35:36,org.apache.axis.handlers.LogHandler in request...
4,29233,AXIS-1745,Decoding of service is broken in org.apache.ax...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,1,2005-01-03 03:34:52,2005-01-03 03:34:52,The following code assumes a lot of things:\n\...

In [34]:
mozilla_df.columns
mozilla_df['status_category']

0       resolved
1       resolved
2       resolved
3       resolved
4       resolved
          ...
9994    resolved
9995    resolved
9996    resolved
9997    resolved
9998    resolved
Name: status_category, Length: 9999, dtype: object

In [42]:
print(mozilla_df.columns)
print(apache_df.columns)
apache_df[['resolution.id', 'resolution.description',
       'resolution.name','statusCategory.name']]

Index(['bug_id', 'creation_date', 'component_name', 'product_name',
       'short_description', 'long_description', 'assignee_name',
       'reporter_name', 'resolution_category', 'resolution_code',
       'status_category', 'status_code', 'update_date', 'quantity_of_votes',
       'quantity_of_comments', 'resolution_date', 'bug_fix_time',
       'severity_category', 'severity_code'],
      dtype='object')
Index(['id', 'key', 'summary', 'resolution.id', 'resolution.description',
       'resolution.name', 'priority.id', 'priority.name', 'labels', 'assignee',
       'status.id', 'status.description', 'status.name', 'statusCategory.id',
       'statusCategory.key', 'statusCategory.colorName', 'statusCategory.name',
       'customfield_12310921', 'creator', 'subtasks', 'reporter',
       'votes.votes', 'issuetype.id', 'issuetype.description',
       'issuetype.name', 'issuetype.subtask', 'project.id', 'project.key',
       'project.name', 'projectCategory.id', 'projectCategory.description',
       'projectCategory.name', 'resolutiondate', 'watches.watchCount',
       'created', 'updated', 'description'],
      dtype='object')

,resolution.id,resolution.description,resolution.name,statusCategory.name
0,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
1,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
2,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
3,NaN,NaN,NaN,To Do
4,NaN,NaN,NaN,To Do
...,...,...,...,...
9995,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9996,3.0,The problem is a duplicate of an existing issue.,Duplicate,Done
9997,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9998,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
9999,1.0,A fix for this issue is checked into the tree ...,Fixed,Done

In [40]:
mozilla_std = pd.DataFrame({
    'bug_id':mozilla_df['bug_id'],
    'title':mozilla_df['short_description'],
    'description':mozilla_df['long_description'],
    'severity':mozilla_df['severity_category'],
    'resolution':mozilla_df['resolution_category'],
    'status':mozilla_df['status_category'],
    'source_dataset':'Mozilla'
}
    
)

eclipse_std = pd.DataFrame({
    'bug_id':eclipse_df['bug_id'],
    'title':eclipse_df['short_description'],
    'description':eclipse_df['long_description'],
    'severity':eclipse_df ['severity_category'],
    'resolution':eclipse_df['resolution_category'],
    'status':eclipse_df['status_category'],
    'source_dataset':'Eclipse'
}
    
)

apache_std = pd.DataFrame({
    'bug_id':apache_df['key'],
    'title':apache_df['summary'],
    'description':apache_df['description'],
    'severity':apache_df ['priority.name'],
    'resolution':apache_df['resolution.name'],
    'status':apache_df['statusCategory.name'],
    'source_dataset':'Apache'
    
})

print('Mozilla:',mozilla_std.shape)
print('Eclipse:',eclipse_std.shape)
print('Apache:',apache_std.shape)

Mozilla: (9999, 7)
Eclipse: (9776, 7)
Apache: (10000, 7)

In [45]:
mozilla_std['stack_trace'] = None
eclipse_std['stack_trace'] = None
apache_std['stack_trace'] = None

mozilla_std['product_component'] = mozilla_df['product_name']
eclipse_std['product_component'] = eclipse_df['product_name']
apache_std['product_component'] = apache_df['project.name']


print(mozilla_std.shape)
print(eclipse_std.shape)
print(apache_std.shape)

mozilla_std.head()

(9999, 9)
(9776, 9)
(10000, 9)

,bug_id,title,description,severity,resolution,status,source_dataset,stack_trace,product_component
0,BUGZILLA-294734,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,blocker,fixed,resolved,Mozilla,None,BUGZILLA
1,OTHER_APPLICATIONS-363323,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS
2,SUPPORT.MOZILLA.ORG-398246,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,blocker,fixed,resolved,Mozilla,None,SUPPORT.MOZILLA.ORG
3,RELEASE_ENGINEERING-525991,Create Major Update from 3.0.15 to 3.5.5,NaN,normal,fixed,resolved,Mozilla,None,RELEASE_ENGINEERING
4,OTHER_APPLICATIONS-318859,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS

In [47]:
knowledge_base_df = pd.concat([mozilla_std,eclipse_std,apache_std], ignore_index = True)
print("Comobo Size " , knowledge_base_df.shape)
knowledge_base_df['source_dataset'].value_counts()

Comobo Size  (29775, 9)

source_dataset
Apache     10000
Mozilla     9999
Eclipse     9776
Name: count, dtype: int64

In [50]:
knowledge_base_df.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_basic_combined.csv" , index = False)
print("Saved Sucessfully")

Saved Sucessfully